### PR TITLE
Join table

### PR DESCRIPTION
**Pull request by Haywayaheadshot**
### What?

I created specialization, visits, and vets tables.

### Why?

To make many-to-many relations so all the tables can share information

### How?
- I created visits, specialization, and vets tables
- I added data to each table.
- I added queries in accordance to the Microverse requirements with screenshots attached below.

# Good day. Please find the screenshots attached below.
2022-12-15_16h08_59

2022-12-15_16h12_39

2022-12-15_16h20_28

2022-12-15_16h21_45

2022-12-15_16h24_00

2022-12-15_16h26_34

2022-12-15_16h28_14

2022-12-15_16h29_56

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
### Hello @Haywayaheadshot 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :stop_sign: 

You have submitted a project, that doesn't have a new microverse [README template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Haywayaheadshot** [comment]
@andersonlebon Thank you for reviewing my project. I have updated my README file.

**Review by Whoistolu — APPROVED** [review]
### Hi @Haywayaheadshot 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
✔️ Descriptive PR
✔️ Meaningful Commit Messages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@Whoistolu Thank you for reviewing my project

**Pull request merged**
